# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_cash_register', '0003_auto_20160810_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(editable=False, max_length=64, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('AB', 'Alfa Click'), ('AC', 'Credit/Debit card'), ('GP', 'Cash via terminal'), ('MA', 'MasterPass'), ('MC', 'Mobile phone account'), ('PB', 'Promsvyazbank online-bank'), ('PC', 'Yandex.Money wallet'), ('SB', 'Sberbank Online'), ('WM', 'WebMoney wallet'), ('QS', 'QiWi wallet')], max_length=2, null=True, verbose_name='Payment method'),
        ),
    ]
